runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /fonts
  static_dir: fonts
- url: /favicons
  static_dir: favicons
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest